### ISSUE TITLE
Application crash when kafka_ex lost connection.

### ISSUE THREAD

**Issue by anoskov** [anoskov/kafka-consumer#10]
Hello all!
I ran into problem using kafka-consumer, when kafka_ex lost connection to kafka, it crashes and breaks consumer. After when connection appears kafka_ex up but consumer no.
One of the ideas use next supervisors spec:
supervisor (1)
-- kafka_ex
-- supervisor (2)
---- consumer
Set strategies one-for-all for supervisor (1) and if kafka_ex dies its restart consumers, but if consumers die this will not affect on kafka_ex.

Another idea use another kafka client - "brod" (https://github.com/klarna/brod)
This library have great api and more stable than kafka_ex.
In addition kafka_ex have bad design. For example memory_leak https://github.com/kafkaex/kafka_ex/issues/141

So in the near future i will develop kafka-consumer version 2.0 using "brod" library. This will make kafka-consumer fault-tolerant and more stable.

Thanks!

**Comment by madshargreave** [comment]
Hi

What is the status on this? I may pick this up if needed

**Comment by anoskov** [comment]
Hello, @madshargreave We done this in our company private repository. But now i don't have time move it here. If u want and have time for this u are welcome 🍻

**Comment by madshargreave** [comment]
@anoskov So you moved to Brod, or just reconfigured the supervision strategy?

**Comment by anoskov** [comment]
@madshargreave moved to brod is preferred way. Its work fine. Ok, i will move new version today. Stay tuned :)

**Comment by madshargreave** [comment]
@anoskov That's awesome, thank you!

**Comment by anoskov** [comment]
@madshargreave i opened PR look this.
