### ISSUE TITLE
Exponential Backoff on `:topic_not_found`

### ISSUE THREAD

**Issue by rawkode** [anoskov/kafka-consumer#8]
Hey,

I was considering forking this library and adding https://github.com/safwank/ElixirRetry, allowing for backoff when `:topic_not_found`

Is this something you'd be interested in adding to this, or should I satisfy my own needs with a fork?

Nice library, thanks!

**Comment by anoskov** [comment]
Hello!
In my case it is better getting error on application start, because a lot of the logic associated with consumer. And if topic not found system is not working properly.
Maybe we should do it optional? As param in config or something...

**Comment by rawkode** [comment]
Yeah, I think if we can make it optional, that is a great route.

In production, yeah; it's a problem if the topic doesn't exist. In my development environment, the topic won't exist until the first message is pushed - that's the situation I'm trying to satisfy :smile: 

If not exponential back-off, then perhaps a flag to create topics on `:topic_not_found`

What do you think?

**Comment by anoskov** [comment]
I didn't found create_topic feature in kafka_ex. We could use kafka scripts for it, but I'm not sure that's a good idea because the need to specify the correct path to the scripts and topic can be created with different parameters as offset numbers, etc... 
I think the best thing we can do is to provide callback which is called on topic_not_found and the user implements the necessary logic in it.

**Comment by anoskov** [comment]
here https://github.com/anoskov/kafka-consumer/blob/master/lib/kafka_consumer/server.ex#L59
we can use something like handler.topic_not_found({topic, partition}, self())
And in this callback we can create topic, send :topic_not_found to caller, send message for back-off (but need add handler for it to caller), etc

**Comment by anoskov** [comment]
I will discuss it with colleagues on weekdays.

**Comment by rawkode** [comment]
Sounds good. Thanks, @anoskov.

**Comment by rawkode** [comment]
Having thought about this over the weekend, I think a callback would be perfect for this.

For now, I will simply override `def handle_info(:topic_not_found, state) do`

**Comment by anoskov** [comment]
@rawkode I talked with colleagues and we decided that raise error if topic not found is best feature for production. If u need handle it in develop env, u can use your fork. Good luck!

**Comment by rawkode** [comment]
No problem, @anoskov. Thanks :+1:
